const countryList = {
    AUD: "AU",
    BGN: "BG",
    BRL: "BR",
    CHF: "CH",
    CZK: "CZ",
    GBP: "GB",
    HKD: "HK",
    HUF: "HU",
    IDR: "ID",
    ILS: "IL",
    INR: "IN",
    ISK: "IS",
    JPY: "JP",
    KRW: "KR",
    MXN: "MX",
    MYR: "MY",
    NZD: "NZ",
    PHP: "PH",
    PLN: "PL",
    RON: "RO",
    SGD: "SG",
    THB: "TH",
    TRY: "TR",
    TTD: "TT",
    USD: "US",
    ZAR: "ZA",
  };